import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { ContextProviders } from "./_components/context-providers";
import { WindowBreakpointProvider } from "./_context/window-breakpoint-context";
import { ClientLayout } from "./_components/client-layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  const locale = await getLocale();

  return (
    <html
      lang={locale}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <NextIntlClientProvider messages={messages}>
          <ContextProviders>
            <WindowBreakpointProvider>
              <ClientLayout>
                {children}
              </ClientLayout>
            </WindowBreakpointProvider>
          </ContextProviders>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
